---
- name: install mailserver
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - dovecot-core
    - dovecot-imapd
    - dovecot-managesieved
    - dovecot-mysql
    - dovecot-sieve
    - postfix
    - postfix-mysql
    - spamassassin
