---
- name: Install mysql
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - mysql-server
    - mysql-client
    - mysql-common
    - python-mysqldb

- mysql_user: name="root"
              password="treetuscanmonk"
              check_implicit_admin=yes
              login_user="root"
              login_password=""
              state=present
