---
- name: Install mysql
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - mysql-server
    - mysql-client
    - mysql-common
    - python-mysqldb

- mysql_user: name="{{ mysql_user }}"
              password="{{ mysql_pass }}"
              check_implicit_admin=yes
              login_user="{{ login_mysql_user }}"
              login_password="{{ login_mysql_pass }"
              state=present
