---
- name: Add ppa:ondrej/php repository
  apt_repository:
    repo: 'ppa:ondrej/php'
- name: Install php5.6-fpm and deps
  apt: name={{ item }} state=present
  with_items:
    - php5.6
    - php5.6-cli
    - php5.6-curl
    - php5.6-fpm
    - php5.6-gd
    - php5.6-json
    - php5.6-mysql
    - php5.6-pgsql
    - php5.6-intl
    - php5.6-readline
